// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrJaMabmf67NJrHw9xhFtVmhkld6LQs5E',
    appId: '1:306409538511:web:ead7ca8a20615c88ab48ba',
    messagingSenderId: '306409538511',
    projectId: 'practice-firebase-154cc',
    authDomain: 'practice-firebase-154cc.firebaseapp.com',
    storageBucket: 'practice-firebase-154cc.firebasestorage.app',
    measurementId: 'G-RCVH8XQ7F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbUUNDZx9KSnjCWZ4g81SvXPhmKuTn9CA',
    appId: '1:306409538511:android:f3b8c78e9328747aab48ba',
    messagingSenderId: '306409538511',
    projectId: 'practice-firebase-154cc',
    storageBucket: 'practice-firebase-154cc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEhh9Ky4nWl0O63ng6OOaBpSQ8m1umoCk',
    appId: '1:306409538511:ios:6c0a3f62e0dfae24ab48ba',
    messagingSenderId: '306409538511',
    projectId: 'practice-firebase-154cc',
    storageBucket: 'practice-firebase-154cc.firebasestorage.app',
    iosBundleId: 'com.example.practiceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEhh9Ky4nWl0O63ng6OOaBpSQ8m1umoCk',
    appId: '1:306409538511:ios:6c0a3f62e0dfae24ab48ba',
    messagingSenderId: '306409538511',
    projectId: 'practice-firebase-154cc',
    storageBucket: 'practice-firebase-154cc.firebasestorage.app',
    iosBundleId: 'com.example.practiceFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrJaMabmf67NJrHw9xhFtVmhkld6LQs5E',
    appId: '1:306409538511:web:16649155f87ec12dab48ba',
    messagingSenderId: '306409538511',
    projectId: 'practice-firebase-154cc',
    authDomain: 'practice-firebase-154cc.firebaseapp.com',
    storageBucket: 'practice-firebase-154cc.firebasestorage.app',
    measurementId: 'G-EJE32XZ1T2',
  );
}
